const sharedColumns = ["id", "user_id", "created_at", "updated_at", "payload"];

export const ENTITY_DEFAULTS = {
  AppSettings: {
    currency: "GBP",
    default_currency: "GBP",
    default_nav_app: "google_maps",
    default_payment_terms_days: 30,
    default_tax_rate: 0,
    email_auto_action: "suggest_only",
    estimate_number_next: 1,
    estimate_number_prefix: "EST-",
    gmail_connected: false,
    invoice_number_next: 1,
    invoice_number_prefix: "INV-",
    invoice_template: 1,
    notification_level: "standard",
    reminder_channel: "in_app",
    tax_rate: 0,
    tax_year_start_month: 4,
  },
  BusinessProfile: {
    business_name: "",
    contact_name: "",
    email: "",
    phone: "",
    address_line_1: "",
    address_line_2: "",
    city: "",
    postcode: "",
    country: "GB",
    tax_id: "",
    bank_name: "",
    bank_account_name: "",
    bank_sort_code: "",
    bank_account_number: "",
    bank_iban: "",
    payment_instructions: "",
    logo: "",
  },
};

export const ENTITY_CONFIG = {
  ActionItem: {
    table: "action_items",
    columns: [
      "item_type",
      "entity_type",
      "entity_id",
      "title",
      "priority",
      "status",
      "action_type",
      "action_target",
      "resolved_at",
      "resolved_by",
      "dismissed_at",
      "snoozed_until",
    ],
    jsonColumns: [],
  },
  AppSettings: {
    table: "app_settings",
    singleton: true,
    columns: [
      "currency",
      "default_currency",
      "default_nav_app",
      "default_payment_terms_days",
      "default_tax_rate",
      "email_auto_action",
      "estimate_number_next",
      "estimate_number_prefix",
      "gmail_connected",
      "invoice_number_next",
      "invoice_number_prefix",
      "invoice_template",
      "notification_level",
      "reminder_channel",
      "tax_rate",
      "tax_year_start_month",
    ],
    jsonColumns: ["notification_prefs"],
  },
  BusinessProfile: {
    table: "business_profiles",
    singleton: true,
    columns: [
      "address",
      "address_line_1",
      "address_line_2",
      "bank_account_name",
      "bank_account_number",
      "bank_iban",
      "bank_name",
      "bank_sort_code",
      "business_name",
      "city",
      "contact_name",
      "country",
      "email",
      "logo",
      "logo_url",
      "payment_instructions",
      "phone",
      "postcode",
      "tax_id",
      "vat_number",
      "website",
    ],
    jsonColumns: [],
  },
  Chart: {
    table: "charts",
    columns: [
      "title",
      "chart_type",
      "key",
      "tempo",
      "feel",
      "genre",
      "content",
      "file_url",
      "file_name",
      "file_type",
      "external_url",
      "notes",
    ],
    jsonColumns: ["linked_event_ids", "tags"],
  },
  Client: {
    table: "clients",
    columns: [
      "name",
      "client_type",
      "city",
      "default_currency",
      "default_fee",
      "default_payment_terms_days",
      "billing_address",
      "notes",
      "late_payment_flag",
      "email_filter_tag",
    ],
    jsonColumns: ["emails", "phones"],
  },
  Document: {
    table: "documents",
    columns: [
      "document_type",
      "document_number",
      "invoice_number",
      "title",
      "client_id",
      "client_email",
      "client_name",
      "work_event_id",
      "status",
      "currency",
      "subtotal",
      "discount_type",
      "discount_value",
      "discount_amount",
      "tax_rate",
      "tax_amount",
      "total",
      "due_date",
      "valid_until",
      "paid_date",
      "paid_amount",
      "payment_method",
      "notes",
      "is_locked",
      "locked_at",
      "unlocked_reason",
      "is_standalone",
      "converted_from_id",
      "sent_date",
      "payment_terms_days",
    ],
    jsonColumns: ["line_items"],
  },
  DocumentActivityLog: {
    table: "document_activity_logs",
    columns: ["document_id", "action", "old_status", "new_status"],
    jsonColumns: ["details"],
  },
  EmailMessage: {
    table: "email_messages",
    columns: ["subject", "from_name", "from_email", "status", "date", "snippet", "body", "thread_id"],
    jsonColumns: [],
  },
  Equipment: {
    table: "equipment",
    columns: ["name", "category", "condition", "serial_number", "notes"],
    jsonColumns: [],
  },
  Payment: {
    table: "payments",
    columns: ["document_id", "amount", "payment_date", "payment_method", "reference", "notes"],
    jsonColumns: [],
  },
  PracticeGoal: {
    table: "practice_goals",
    columns: ["title", "description", "category", "completed", "completed_date", "target_date"],
    jsonColumns: [],
  },
  PracticeSession: {
    table: "practice_sessions",
    columns: [
      "date",
      "duration_minutes",
      "notes",
      "session_notes",
      "goal_id",
      "work_event_id",
      "energy_rating",
      "linked_gig_id",
    ],
    jsonColumns: ["items"],
  },
  Reminder: {
    table: "reminders",
    columns: ["title", "date", "time", "status", "notes", "linked_entity_type", "linked_entity_id"],
    jsonColumns: [],
  },
  Setlist: {
    table: "setlists",
    columns: ["title", "notes"],
    jsonColumns: ["items"],
  },
  Notification: {
    table: "notifications",
    columns: ["type", "title", "body", "entity_type", "url", "read_at"],
    jsonColumns: [],
  },
  WorkEvent: {
    table: "work_events",
    columns: [
      "title",
      "event_type",
      "status",
      "date",
      "time",
      "start_time",
      "end_time",
      "client_id",
      "location_address",
      "location_name",
      "base_price",
      "total_price",
      "currency",
      "notes",
      "is_recurring",
      "recurrence_id",
      "recurrence_index",
      "google_calendar_event_id",
      "base_price_locked",
      "duration_hours",
      "linked_gig_id",
      "practice_plan",
      "practice_goal_id",
      "practice_logged",
      "practice_session_id",
      "practice_skipped",
    ],
    jsonColumns: ["adjustments", "equipment_checklist", "recurrence_rule"],
  },
};

export const ENTITY_COLUMNS = Object.fromEntries(
  Object.entries(ENTITY_CONFIG).map(([entityName, config]) => [
    entityName,
    new Set([...sharedColumns, ...(config.columns || []), ...(config.jsonColumns || [])]),
  ])
);

